name: 社員情報の削除・アーカイブ
description: 退職や誤登録の際に社員データを処理します
title: "[Delete] {名前}"
labels: ["employee-delete"]
body:
  - type: markdown
    attributes:
      value: |
        社員情報の削除またはアーカイブを申請します。
        - **アーカイブ**: 退職者としてデータを残します（推奨）
        - **削除**: 誤登録などを完全に消去します

  - type: dropdown
    id: name
    attributes:
      label: 対象社員名
      description: 削除・アーカイブする社員を選択してください
      options:
        - 上遼太郎
        - 佐藤傑
        - 小島遼祐
        - 小松田真伍
        - 小林翔
        - 戸塚直道
        - 杉本光一
        - 榎本詩織
        - 櫻井志保
        - 田浦裕樹
        - 菅野聖也
        - 藤井芙美子
        - 貴志雪乃
        - 鈴木悠斗
        - 開米 敦則
        - 青木淳一郎
    validations:
      required: true

  - type: dropdown
    id: action_type
    attributes:
      label: 処理種別
      options:
        - "Archive (退職:データ残す)"
        - "Delete (誤登録:完全に消す)"
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: 理由
      description: 退職理由や削除理由（任意）
    validations:
      required: false
