name: キャリア・目標登録（年次更新）
description: 年ごとのキャリア目標とスキル状況を登録・更新します
title: "[Career] 年次更新"
labels: ["employee-update"]
body:
  - type: markdown
    attributes:
      value: |
        年次キャリア情報の更新ありがとうございます。
        この情報は社内マッチングやメンター推薦などに活用されます。

  - type: dropdown
    id: name
    attributes:
      label: お名前
      description: 自分の名前を選択してください（選択肢にない場合はマネージャーに初期登録を依頼してください）
      options:
        - 上遼太郎
        - 佐藤傑
        - 小島遼祐
        - 小松田真伍
        - 小林翔
        - 戸塚直道
        - 杉本光一
        - 櫻井志保
        - 田浦裕樹
        - 菅野聖也
        - 藤井芙美子
        - 貴志雪乃
        - 鈴木悠斗
        - 開米 敦則
        - 青木淳一郎
    validations:
      required: true

  - type: textarea
    id: self_intro
    attributes:
      label: 自己紹介 / キャリア詳細
      description: |
        あなたの経歴、強み、最近の興味、今後の目標、趣味、最近の悩みなど、**なんでも自由に書いてください**。
        形式にこだわる必要はありません。AIが内容を理解して整理します。
      placeholder: |
        (例)
        現在はGo言語を中心にバックエンド開発をしていますが、実はReactも書けます。
        最近はRustに興味があり、週末に個人的なアプリを作っています。
        来年は特定技術のスペシャリストというよりは、チームを率いるEM的な立ち位置に挑戦したいです。
        趣味はサウナとキャンプです。最近は子供が生まれたので育休取得についても相談したいです。
    validations:
      required: true
