name: キャリア・目標登録（年次更新）
description: 年ごとのキャリア目標とスキル状況を登録・更新します
title: "[Career] 年次更新"
labels: ["employee-update"]
body:
  - type: markdown
    attributes:
      value: |
        年次キャリア情報の更新ありがとうございます。
        この情報は社内マッチングやメンター推薦などに活用されます。

  - type: dropdown
    id: name
    attributes:
      label: お名前
      description: 自分の名前を選択してください（選択肢にない場合はマネージャーに初期登録を依頼してください）
      options:
        - 小林翔
        - 杉本光一
        - 櫻井志保
        - 田浦裕樹
        - 開米 敦則
        - 青木淳一郎
    validations:
      required: true

  - type: dropdown
    id: job
    attributes:
      label: 職種
      options:
        - Engineer
        - Designer
        - Sales
        - PM
        - Corporate
        - EM
        - QA
        - HR
        - Other
    validations:
      required: true

  - type: input
    id: like_tech
    attributes:
      label: 好きな技術
      description: モチベーションの源泉となる技術。業務外でも触りたい、学びたいもの。
      placeholder: React, Rust, 生成AI
    validations:
      required: true

  - type: input
    id: dislike_tech
    attributes:
      label: 嫌いな技術
      description: アサインを避けてほしい技術。苦手なもの、もうやりたくないもの。
      placeholder: jQuery, レガシーPHP
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        ## 次に見据えたあなたのゴール（SMART）
        以下の5つの観点から、1年以内に達成したい目標を記入してください。

  - type: input
    id: smart_s
    attributes:
      label: "S (Specific: 具体的)"
      description: 何を達成するのか？
      placeholder: 例) Go言語を使ったマイクロサービス開発ができるようになる
    validations:
      required: true

  - type: input
    id: smart_m
    attributes:
      label: "M (Measurable: 測定可能)"
      description: どうなったら成功と言えるか？
      placeholder: 例) 実装したAPIが本番稼働し、チームメンバーがコードレビューで承認してくれる
    validations:
      required: true

  - type: input
    id: smart_a
    attributes:
      label: "A (Achievable: 達成可能)"
      description: どうやって実現するか？
      placeholder: 例) 週3時間の学習時間を確保し、社内メンターにサポートしてもらう
    validations:
      required: true

  - type: input
    id: smart_r
    attributes:
      label: "R (Relevant: 関連性)"
      description: なぜこれをやるのか？
      placeholder: 例) 現在のプロジェクトでGoへの移行が予定されており、自分のスキルセットにも合う
    validations:
      required: true

  - type: input
    id: smart_t
    attributes:
      label: "T (Time-bound: 期限)"
      description: いつまでに達成するか？
      placeholder: 例) 2026年12月末までに最初のサービスをリリース
    validations:
      required: true
